log:
  level: DEBUG   
  format: common

accessLog:
  format: common

entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"

providers:
  docker:
    watch: true
    endpoint: "tcp://socket-proxy:2375"
    exposedByDefault: false
  file:
    directory: /etc/traefik/config
    watch: true

certificatesResolvers:
  tlsresolver:
    tailscale: {}
  cloudflare:
    acme:
      email: admin@mcube.uk
      storage: /certs/acme.json
      caServer: https://acme-v02.api.letsencrypt.org/directory # prod (default)
      # caServer: https://acme-staging-v02.api.letsencrypt.org/directory # staging
      dnsChallenge:
        provider: cloudflare
        delayBeforeCheck: 2