services:
  traefik:
    image: traefik:latest
    container_name: traefik
    restart: unless-stopped
    command:
    - "--configFile=/etc/traefik/config/static.yml"
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik/config:/etc/traefik/config:ro
      - ./traefik/logs:/traefik/logs
      - ./letsencrypt:/letsencrypt:rw
    environment:
      - TZ=Asia/Manila
    networks:
      - proxy
networks:
  proxy:
    external: false