services:
  socket-proxy:
    image: tecnativa/docker-socket-proxy
    environment:
      CONTAINERS: 1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - proxy

  traefik:
    image: traefik:latest
    container_name: traefik
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    command:
    - "--configFile=/etc/traefik/config/static.yml"
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./traefik/config:/etc/traefik/config:ro
      - ./traefik/logs:/traefik/logs
      - ./letsencrypt:/letsencrypt:rw
    environment:
      - TZ=Asia/Manila
    networks:
      - proxy
networks:
  proxy:
    external: true