# You need tailscale running for the host machine
services:
  syncthing:
    image: syncthing/syncthing
    container_name: syncthing
    hostname: ovh-server-2
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ./st-sync:/var/syncthing
      - ${MOUNT_DIR}:/mnt/srv
    network_mode: host
    restart: unless-stopped
    healthcheck:
      test: curl -fkLsS -m 2 127.0.0.1:8384/rest/noauth/health | grep -o --color=never OK || exit 1
      interval: 1m
      timeout: 10s
      retries: 3
