global:
  scrape_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets: ["alertmanager:9093"]

rule_files:
  - recording-rules.yml
  - alerting-rules.yml

scrape_configs:
  - job_name: 'node_exporter'
    static_configs:
      - targets: ['node_exporter:9100']

  - job_name: traefik
    metrics_path: /metrics
    static_configs:
      - targets: ['reverse-proxy:8080']
  
  - job_name: 'adonisjs-app'
    metrics_path: /metrics
    static_configs:
      - targets: ['adonisjs:3333']

  - job_name: prometheus
    static_configs:
      - targets: ["localhost:9090"]
