http:
  routers:
    server:
      rule: "Host(`api.ferd.mcube.uk`)"
      entryPoints:
        - websecure
      middlewares:
        - cors
        - security
        - block-sensitive
        - forwarded-headers
      tls:
        certResolver: tlsresolver
      service: api-service

  services:
    api-service:
      loadBalancer:
        passHostHeader: true # This fixed something, idk what
        # serversTransport: "insecure-skip"
        servers:
          - url: "http://ferd.home.production.mcube.uk"  # Home server exposed via Tailscale

  middlewares:
    forwarded-headers:
      headers:
        customRequestHeaders:
          X-Forwarded-Proto: "https"
    cors:
      headers:
        accessControlAllowOriginList:
          - "https://ferd.mcube.uk"
        accessControlAllowMethods:
          - "GET"
          - "POST"
          - "PUT"
          - "DELETE"
        accessControlAllowHeaders:
          - Content-Type
          - Authorization
        accessControlAllowCredentials: true
        accessControlMaxAge: 100
        addVaryHeader: true

    security:
      headers:
        browserXssFilter: true
        contentTypeNosniff: true
        forceSTSHeader: true
        stsSeconds: 31536000
        stsIncludeSubdomains: true
        stsPreload: true
        frameDeny: true
        sslRedirect: true

    block-sensitive:
      redirectRegex:
        regex: "^.*(\\.env|\\.git|docker-compose\\.yml|\\.htaccess|\\.htpasswd|config\\.json).*$"
        replacement: "https://www.youtube.com/watch?v=xvFZjo5PgG0"
        permanent: true
