http:
  routers:
    # FERD Backend
    server-ferd:
      rule: "Host(`api.ferd.mcube.uk`)"
      entryPoints:
        - websecure
      middlewares:
        - cors-ferd
        - security
        - block-sensitive
        - forwarded-headers
      tls:
        certResolver: tlsresolver
      service: api-ferd-service
    
    # PayMongo Webhook Test URL
    server-portal:
      rule: "Host(`api.portal.mcube.uk`)"
      entryPoints:
        - websecure
      middlewares:
        - cors-portal
        - security
        - block-sensitive
        - forwarded-headers
      tls:
        certResolver: tlsresolver
      service: api-portal-service

    # N8n self-hosted instance
    n8n:
      rule: "Host(`n8n.mcube.uk`)"
      entryPoints:
        - websecure
      middlewares:
        - security
        - block-sensitive
        - forwarded-headers
      tls:
        certResolver: tlsresolver
      service: n8n-service

  services:
    api-ferd-service:
      loadBalancer:
        passHostHeader: true # This fixed something, idk what
        # serversTransport: "insecure-skip"
        servers:
          - url: "http://ferd.home.production.mcube.uk"  # Home server exposed via Tailscale
    
    api-portal-service:
      loadBalancer:
        passHostHeader: true # This fixed something, idk what
        # serversTransport: "insecure-skip"
        servers:
          - url: "http://desktop.hinny-carat.ts.net:3001"  # Home server exposed via Tailscale
    
    n8n-service:
      loadBalancer:
        passHostHeader: true # This fixed something, idk what
        # serversTransport: "insecure-skip"
        servers:
          - url: "http://n8n.home.development.mcube.uk"  # Home server exposed via Tailscale

  middlewares:
    forwarded-headers:
      headers:
        customRequestHeaders:
          X-Forwarded-Proto: "https"
    cors-ferd:
      headers:
        accessControlAllowOriginList:
          - "https://ferd.mcube.uk"
        accessControlAllowMethods:
          - "GET"
          - "POST"
          - "PUT"
          - "DELETE"
          - "PATCH"
        accessControlAllowHeaders:
          - Content-Type
          - Authorization
        accessControlAllowCredentials: true
        accessControlMaxAge: 100
        addVaryHeader: true
    cors-portal:
      headers:
        accessControlAllowOriginList:
          - "*"
        accessControlAllowMethods:
          - "GET"
          - "POST"
          - "PUT"
          - "DELETE"
          - "PATCH"
        accessControlAllowHeaders:
          - Content-Type
          - Authorization
        accessControlAllowCredentials: true
        accessControlMaxAge: 100
        addVaryHeader: true

    security:
      headers:
        browserXssFilter: true
        contentTypeNosniff: true
        forceSTSHeader: true
        stsSeconds: 31536000
        stsIncludeSubdomains: true
        stsPreload: true
        frameDeny: true
        sslRedirect: true

    block-sensitive:
      redirectRegex:
        regex: "^.*(\\.env|\\.git|docker-compose\\.yml|\\.htaccess|\\.htpasswd|config\\.json).*$"
        replacement: "https://www.youtube.com/watch?v=xvFZjo5PgG0"
        permanent: true
