http:
  routers:
    ferd:
      rule: "Host(`api.ferd.mcube.uk`)"
      entryPoints: [websecure]
      middlewares: [cors-ferd, default-chain]
      tls:
        certResolver: tlsresolver
      service: ferd-service
    
    n8n:
      rule: "Host(`auto.mcube.uk`)"
      entryPoints: [websecure]
      middlewares: [default-chain]
      tls:
        certResolver: tlsresolver
      service: n8n-service
    
  services:
    ferd-service:
      loadBalancer:
        passHostHeader: true
        servers:
          - url: "http://ferd.home.production.mcube.uk"
    
    n8n-service:
      loadBalancer:
        passHostHeader: true
        servers:
          - url: "http://auto.home.development.mcube.uk"
    
  middlewares:
    cors-base:
      headers:
        accessControlAllowMethods: ["GET", "POST", "PUT", "DELETE", "PATCH", "OPTIONS"]
        accessControlAllowHeaders: ["Content-Type", "Authorization"]
        accessControlAllowCredentials: true
        accessControlMaxAge: 100
        addVaryHeader: true

    cors-ferd-allow:
      headers:
        accessControlAllowOriginList:
          - "https://ferd.mcube.uk"

    cors-ferd:
      chain:
        middlewares:
          - cors-ferd-allow
          - cors-base

    forwarded-headers:
      headers:
        customRequestHeaders:
          X-Forwarded-Proto: "https"

    security:
      headers:
        browserXssFilter: true
        contentTypeNosniff: true
        forceSTSHeader: true
        stsSeconds: 31536000
        stsIncludeSubdomains: true
        stsPreload: true
        frameDeny: true
        sslRedirect: true

    block-sensitive:
      redirectRegex:
        regex: "^.*(\\.env|\\.git|docker-compose\\.yml|\\.htaccess|\\.htpasswd|config\\.json).*$"
        replacement: "https://www.youtube.com/watch?v=xvFZjo5PgG0"
        permanent: true

    default-chain:
      chain:
        middlewares:
          - security
          - block-sensitive
          - forwarded-headers
