services:
  tailscale:
    image: tailscale/tailscale:latest
    container_name: tailscale
    hostname: dockge
    environment:
      TS_AUTHKEY: ${TS_AUTHKEY}
      TS_STATE_DIR: /var/lib/tailscale
      TS_USERSPACE: false
      TS_SERVE_CONFIG: /config/serve.json
      TS_EXTRA_ARGS: --reset
    volumes:
      # Since the port where the application is being exposed is on 5001
      # We must put 127.0.0.1:5001 on the serve.json file
      - ${PROJECT_DIR}/serve.json:/config/serve.json
      - ${PROJECT_DIR}/tailscale/state:/var/lib/tailscale
    devices:
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - net_admin
      - sys_module
    restart: unless-stopped

  dockge:
    image: louislam/dockge:1
    restart: unless-stopped
    network_mode: service:tailscale
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data:/app/data
      # Stacks Directory
      # ⚠️ READ IT CAREFULLY. If you did it wrong, your data could end up writing into a WRONG PATH.
      # ⚠️ 1. FULL path only. No relative path (MUST)
      # ⚠️ 2. Left Stacks Path === Right Stacks Path (MUST)
      - ./stacks:/stacks
    environment:
      # Tell Dockge where to find the stacks
      - DOCKGE_STACKS_DIR=/stacks